name: "Run Tests"

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3]
        dependency-version: [prefer-lowest, prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }}

    steps:
      - uses: actions/checkout@v1

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.1.1
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: xdebug

      - name: Install Dependencies
        run: composer u --${{ matrix.dependency-version }} --ansi --no-interaction --no-suggest --prefer-dist

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit

      - name: Check logs
        run: |
          echo '--------------- Begin > lumen.log ---------------';
          cat storage/logs/lumen.log
          echo '--------------- End   > lumen.log ---------------';
